"""create initial tables

Revision ID: a4d21c2b34b5
Revises: 
Create Date: 2026-05-25 21:20:29.017694

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4d21c2b34b5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('request_type', sa.String(length=255), nullable=False),
        sa.Column(
            'patrimony_value',
            sa.Numeric(precision=14, scale=2),
            nullable=False
        ),
        sa.Column('status', sa.String(length=100), nullable=False),
        sa.Column('priority', sa.String(length=100), nullable=True),
        sa.Column('pipefy_card_id', sa.String(length=100), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table(
        'pipefy_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('operation', sa.String(length=100), nullable=False),
        sa.Column('payload_json', sa.JSON(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_pipefy_requests_id'),
        'pipefy_requests', ['id'],
        unique=False
    )
    op.create_table('webhook_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=255), nullable=False),
        sa.Column('card_id', sa.String(length=255), nullable=False),
        sa.Column('customer_email', sa.String(length=255), nullable=False),
        sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'processed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_webhook_events_customer_email'),
        'webhook_events',
        ['customer_email'],
        unique=False
    )
    op.create_index(
        op.f('ix_webhook_events_event_id'),
        'webhook_events',
        ['event_id'],
        unique=True
    )
    op.create_index(
        op.f('ix_webhook_events_id'),'webhook_events', ['id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(
        op.f('ix_webhook_events_customer_email'),
        table_name='webhook_events'
    )
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_pipefy_requests_id'), table_name='pipefy_requests')
    op.drop_table('pipefy_requests')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
